### ISSUE TITLE
[philoskim/debux-stubs "0.5.6"] cannot be found in Clojars

### ISSUE THREAD

**Issue by zhanghuabin** [philoskim/debux-stubs#1]
Hi,

    I can only find 0.5.5 in clojars, so I guess 0.5.6 is not be released correctly.

    Thanks

**Comment by philoskim** [comment]
Sorry for this issue!

I forgot to upload the new version 0.5.6 of debux-stubs on Clojars.

I have just uploaded the new version and thank you for the reporting!
